# Generated by Django 3.0 on 2020-09-23 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_dislikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='Аватарка'),
            preserve_default=False,
        ),
    ]
