# Generated by Django 3.0 on 2020-09-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200923_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(default='https://vk.com/images/soviet_200.png', verbose_name='Аватарка'),
        ),
    ]
