# Generated by Django 3.0 on 2020-10-01 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20200930_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Прочитавшие'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
